
// This is an autogenerated file from Firebase Studio.
'use server';
/**
 * @fileOverview A translation AI agent. Translates text into sanskrit.
 *
 * - translateToSanskrit - A function that handles the translation process.
 * - TranslateToSanskritInput - The input type for the translateToSanskrit function.
 * - TranslateToSanskritOutput - The return type for the translateToSanskrit function.
 */

import { ai } from '@/app/genkit';
import { googleAI } from '@genkit-ai/googleai';
import {
  type TranslateToSanskritInput,
  TranslateToSanskritInputSchema,
  type TranslateToSanskritOutput,
  TranslateToSanskritOutputSchema,
} from '@/types/ai.types';

export type { TranslateToSanskritInput, TranslateToSanskritOutput };

const prompt = ai.definePrompt({
    name: 'translateToSanskritPrompt',
    model: googleAI.model('gemini-1.5-flash'),
    input: {schema: TranslateToSanskritInputSchema},
    output: {schema: TranslateToSanskritOutputSchema},
    prompt: `You are a highly skilled translator specializing in Sanskrit. Your task is to translate the given text into accurate and grammatically correct Sanskrit.

  Text to translate: {{{text}}}`,
});

const translateToSanskritFlow = ai.defineFlow(
    {
      name: 'translateToSanskritFlow',
      inputSchema: TranslateToSanskritInputSchema,
      outputSchema: TranslateToSanskritOutputSchema,
    },
    async input => {
      const {output} = await prompt(input);
      if (!output) {
        throw new Error("The AI model failed to return a translation.");
      }
      return output;
    }
);

export async function translateToSanskrit(
  input: TranslateToSanskritInput
): Promise<TranslateToSanskritOutput> {
  return translateToSanskritFlow(input);
}
